/* Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/
package main
import "fmt"
func main() { 
fmt.Println(fibonacci(4000000))
}
func fibonacci(n int) int {
sum := 0 b := 1 c := 0 output := 0 
for c < n {
c = sum + b  
if c > n {
break  
}  
if c%2 == 0 {
output += c  
}  
b = sum  sum = c
} return output
}
